import{useState,useEffect}from"react";import{db}from"../src/lib/firebase";import{doc,setDoc,collection,getDocs,updateDoc,getDoc}from"firebase/firestore";
function calcPoints(s){let pts=0;const r=parseInt(s.runs||0),balls=parseInt(s.balls||0),fours=parseInt(s.fours||0),sixes=parseInt(s.sixes||0),w=parseInt(s.wickets||0),overs=parseFloat(s.overs||0),maidens=parseInt(s.maidens||0),eco=parseFloat(s.economy||0),catches=parseInt(s.catches||0),stumpings=parseInt(s.stumpings||0),runouts=parseInt(s.runouts||0);pts+=r;pts+=fours;pts+=sixes*2;if(r>=100)pts+=16;else if(r>=50)pts+=8;else if(r>=30)pts+=4;if(r===0&&balls>0)pts-=2;if(balls>=10){const sr=(r/balls)*100;if(sr>=170)pts+=6;else if(sr>=150)pts+=4;else if(sr>=130)pts+=2;else if(sr<50)pts-=6;else if(sr<60)pts-=4;else if(sr<70)pts-=2;}pts+=w*25;if(w>=5)pts+=16;else if(w>=4)pts+=8;else if(w>=3)pts+=4;pts+=maidens*4;if(overs>=2&&eco>0){if(eco<5)pts+=6;else if(eco<6)pts+=4;else if(eco<7)pts+=2;else if(eco>=12)pts-=6;else if(eco>=11)pts-=4;else if(eco>=10)pts-=2;}pts+=catches*8;pts+=stumpings*12;pts+=runouts*6;return pts;}
const MATCHES=["RR_MI_2026_M13","DC_GT_2026_M14","KKR_LSG_2026_M15","RR_RCB_2026_M16","PBKS_SRH_2026_M17","CSK_DC_2026_M18"];
const FIELDS=[{k:"runs",l:"Runs"},{k:"balls",l:"Balls"},{k:"fours",l:"4s"},{k:"sixes",l:"6s"},{k:"wickets",l:"Wkts"},{k:"overs",l:"Overs"},{k:"economy",l:"Eco"},{k:"catches",l:"Catch"},{k:"stumpings",l:"St"},{k:"runouts",l:"RO"}];
export default function ManualScore(){
const[secret,setSecret]=useState("");const[authed,setAuthed]=useState(false);const[matchId,setMatchId]=useState("RR_MI_2026_M13");const[players,setPlayers]=useState([]);const[stats,setStats]=useState({});const[saving,setSaving]=useState(false);const[toast,setToast]=useState("");
useEffect(()=>{if(!authed)return;const t1=matchId.split("_")[0];const t2=matchId.split("_")[1];fetch("/api/matches").then(r=>r.json()).then(d=>{const s1=(d[t1]||[]).map(p=>({id:`${t1}_${p.name.replace(/\s+/g,"_")}`,name:p.name,team:t1}));const s2=(d[t2]||[]).map(p=>({id:`${t2}_${p.name.replace(/\s+/g,"_")}`,name:p.name,team:t2}));setPlayers([...s1,...s2]);setStats({});});},[authed,matchId]);
function updateStat(pid,field,val){setStats(prev=>({...prev,[pid]:{...(prev[pid]||{}),[field]:val}}));}
async function save(){setSaving(true);const scorecard={};players.forEach(p=>{const s=stats[p.id]||{};scorecard[p.id]={...s,name:p.name,basePts:calcPoints(s)};});await setDoc(doc(db,"scorecards",matchId),{scorecard,matchId,updatedAt:new Date().toISOString()});const contestsSnap=await getDocs(collection(db,"contests"));for(const cd of contestsSnap.docs){if(cd.data().matchId!==matchId)continue;const lbSnap=await getDocs(collection(db,"contests",cd.id,"leaderboard"));const updates=[];for(const ld of lbSnap.docs){const ts=await getDoc(doc(db,"teams",ld.id));if(!ts.exists())continue;const{players:tp,captainId,vcId}=ts.data();if(!tp)continue;let total=0;tp.forEach(pid=>{const base=scorecard[pid]?.basePts||0;total+=pid===captainId?base*2:pid===vcId?Math.round(base*1.5):base;});updates.push({ref:ld.ref,total});}updates.sort((a,b)=>b.total-a.total);for(let i=0;i<updates.length;i++)await updateDoc(updates[i].ref,{totalScore:updates[i].total,rank:i+1,lastUpdated:new Date()});}setSaving(false);setToast("Saved!");setTimeout(()=>setToast(""),3000);}
const s={wrap:{maxWidth:900,margin:"2rem auto",padding:"0 1rem",fontFamily:"sans-serif"},inp:{padding:"8px",border:"1px solid #ccc",borderRadius:8,fontSize:13},btn:{padding:"10px 20px",borderRadius:8,border:"none",cursor:"pointer",background:"#FF6B00",color:"#fff",fontSize:14,fontWeight:600}};
if(!authed)return(<div style={s.wrap}><h2>Manual Scoring</h2><input style={{...s.inp,width:300,marginRight:8}} type="password" placeholder="Admin secret" value={secret} onChange={e=>setSecret(e.target.value)}/><button style={s.btn} onClick={()=>{if(secret==="ipladmin2026")setAuthed(true);}}>Login</button></div>);
return(<div style={s.wrap}>{toast&&<div style={{position:"fixed",bottom:20,right:20,background:"#4CAF50",color:"#fff",padding:"10px 16px",borderRadius:8}}>{toast}</div>}<h2>Manual Scoring</h2><select style={{...s.inp,marginBottom:16,width:300}} value={matchId} onChange={e=>setMatchId(e.target.value)}>{MATCHES.map(m=><option key={m}>{m}</option>)}</select><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr style={{background:"#FF6B00",color:"#fff"}}><th style={{padding:"8px",textAlign:"left"}}>Player</th>{FIELDS.map(f=><th key={f.k} style={{padding:"8px"}}>{f.l}</th>)}<th style={{padding:"8px"}}>PTS</th></tr></thead><tbody>{players.map((p,i)=>{const st=stats[p.id]||{};const pts=calcPoints(st);return(<tr key={p.id} style={{background:i%2===0?"#fff":"#fafafa",borderBottom:"1px solid #eee"}}><td style={{padding:"6px 8px"}}><b>{p.team}</b> {p.name}</td>{FIELDS.map(f=><td key={f.k} style={{padding:"4px"}}><input type="number" min="0" style={{width:45,padding:"3px",border:"1px solid #ddd",borderRadius:4,fontSize:11,textAlign:"center"}} value={st[f.k]||""} onChange={e=>updateStat(p.id,f.k,e.target.value)}/></td>)}<td style={{padding:"6px 8px",fontWeight:700,color:pts>0?"#FF6B00":pts<0?"red":"#666"}}>{pts}</td></tr>);})}</tbody></table></div><button style={{...s.btn,marginTop:16,width:"100%"}} onClick={save} disabled={saving}>{saving?"Saving...":"Calculate & Save Scores"}</button></div>);}
